### ISSUE TITLE
Care to publish this to npm?

### ISSUE THREAD

**Issue by leesei** [nodayoshikazu/jsonselect-cli#1]
I was looking for cli wrappers for the JSONSelect and found this repo.
Can you also publish it to NPM so we can `npm -g jsonselect-cli`?

Other improvements:
`should` and `coffee-script` should be `devDependencies`
[JSONSelect](https://www.npmjs.com/package/JSONSelect) is on NPM and can be added as dependencies

**Comment by nodayoshikazu** [comment]
Ok, I have published this module to NPM. This is the first time ever to publish a Node module for me so I am not sure what will happen. Please let me know if you encounter any issues.

Thanks

**Comment by leesei** [comment]
Thanks for the prompt action.
I test the package and it is not working yet.

Here are the TODOs:
- `npm install JSONSelect --save` (this make the npm package not working)
- "devDependencies" is duplicated
- missing comma before second "devDependencies"
- rename `lib/index.js` to `/jsonselect-cli` and change `"main"` in package.json
- add `"preferGlobal": true`

I'll also look into it and see what I can do.

[Here's](http://browsenpm.org/package.json) a reference to package.json.
